// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASjz1AChUr2yN_dldx_ytwllkOsfLhdxU',
    appId: '1:367379159070:web:608e0eb806b7fa5244760f',
    messagingSenderId: '367379159070',
    projectId: 'scheduler-19bde',
    authDomain: 'scheduler-19bde.firebaseapp.com',
    storageBucket: 'scheduler-19bde.firebasestorage.app',
    measurementId: 'G-6F0R4ESLSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASTkW0x5WpjDssHMiJ23Eqqkkx3Tn6nNo',
    appId: '1:367379159070:android:be85530a0353e81544760f',
    messagingSenderId: '367379159070',
    projectId: 'scheduler-19bde',
    storageBucket: 'scheduler-19bde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPHBUk7U24wQDd_58nVNVid-Y6VW5COYU',
    appId: '1:367379159070:ios:a0d3f3d1cda2f82f44760f',
    messagingSenderId: '367379159070',
    projectId: 'scheduler-19bde',
    storageBucket: 'scheduler-19bde.firebasestorage.app',
    iosBundleId: 'com.example.scheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPHBUk7U24wQDd_58nVNVid-Y6VW5COYU',
    appId: '1:367379159070:ios:a0d3f3d1cda2f82f44760f',
    messagingSenderId: '367379159070',
    projectId: 'scheduler-19bde',
    storageBucket: 'scheduler-19bde.firebasestorage.app',
    iosBundleId: 'com.example.scheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASjz1AChUr2yN_dldx_ytwllkOsfLhdxU',
    appId: '1:367379159070:web:0b2639154de7120b44760f',
    messagingSenderId: '367379159070',
    projectId: 'scheduler-19bde',
    authDomain: 'scheduler-19bde.firebaseapp.com',
    storageBucket: 'scheduler-19bde.firebasestorage.app',
    measurementId: 'G-NY5CE141BC',
  );
}
